amendments to comply with Erlang/OTP version: 22
NSO-developer/genet pull request #9
Opened 2020-09-06 13:17 UTC by lucecisco

2020-09-07 16:39 UTC, martin-volf requested changes

2020-09-07 16:39 UTC, martin-volf commented on src/erlang-lib/ec_genet/src/ec_genet_server.erl
>          case Trace of
I think this cannot compile, the variable is called `CallmapTrace` in the function head.

2020-09-07 16:44 UTC, martin-volf commented
I think the change should not go to the master branch, since it would not compile/work with pre-5.4 NSO versions, it should go to a branch like nso-5.4 or something like that; @janlindblad, can you create the branch so that the pull-request can target it?

2020-09-11 15:07 UTC, janlindblad commented
Created branch "pre-5.4" with latest commit as branch point. Martin, can you make the necessary changes?

2020-11-05 08:08 UTC, merged

2020-11-05 08:10 UTC, janlindblad commented
Merged Martin's fix for OTP 22